version: "3"

services:
  app:
    build: .
    ports: 
      - "8000:8000"
    volumes: # updates changes to docker image in realtime
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
